# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

anticlustering <- function(n, k, d_count, d_sorted, d_matrix) {
    .Call(`_RcppTestPackage_anticlustering`, n, k, d_count, d_sorted, d_matrix)
}

solve_k_graph_coloring_anticlust <- function(selection_index, k, edge_count, edge_table_u, edge_table_v, target_groups_sizes, number_of_threads, number_of_solutions, symmetry_breaking) {
    .Call(`_RcppTestPackage_solve_k_graph_coloring_anticlust`, selection_index, k, edge_count, edge_table_u, edge_table_v, target_groups_sizes, number_of_threads, number_of_solutions, symmetry_breaking)
}

solve_k_graph_coloring_simple_next_call <- function(selection_index, k, edge_count, edge_table_u, edge_table_v, target_groups_sizes, number_of_threads, number_of_solutions) {
    .Call(`_RcppTestPackage_solve_k_graph_coloring_simple_next_call`, selection_index, k, edge_count, edge_table_u, edge_table_v, target_groups_sizes, number_of_threads, number_of_solutions)
}

solve_k_graph_coloring_repeated_next_calls_and_random_pick <- function(selection_index, k, edge_count, edge_table_u, edge_table_v, target_groups_sizes, number_of_threads, number_of_solutions, number_of_querries) {
    .Call(`_RcppTestPackage_solve_k_graph_coloring_repeated_next_calls_and_random_pick`, selection_index, k, edge_count, edge_table_u, edge_table_v, target_groups_sizes, number_of_threads, number_of_solutions, number_of_querries)
}

solve_k_graph_coloring <- function(selection_index, k, edge_count, edge_table_u, edge_table_v, target_groups_sizes, number_of_threads, number_of_solutions) {
    .Call(`_RcppTestPackage_solve_k_graph_coloring`, selection_index, k, edge_count, edge_table_u, edge_table_v, target_groups_sizes, number_of_threads, number_of_solutions)
}

maximize_dispersion_gecode_cpp <- function(n, k, d_count, d_sorted, d_matrix, target_groups_sizes, number_of_threads, maximum_number_of_solutions) {
    .Call(`_RcppTestPackage_maximize_dispersion_gecode_cpp`, n, k, d_count, d_sorted, d_matrix, target_groups_sizes, number_of_threads, maximum_number_of_solutions)
}

